### ISSUE TITLE
被触发的Workers似乎总会发生错误，在编辑器中测试没问题

### ISSUE THREAD

**Issue by lwd-temp** [SunYufei/freenom#11]
手动修改配置Webhook，收到的日志如下：
```
scheduled date 1659673075000 
cookie 【删节】
get login status failed 
token null 
domains {} 
```

Workers是否存在请求限制？似乎只有第一个请求成功？

**Comment by SunYufei** [comment]
从日志来看，可能是 Workers 端 Freenom 登录失败

**Comment by lwd-temp** [comment]
多次测试来看，点击编辑器中的手动启动按钮就不会发生错误，cron每次都会发生错误，这个错误也和我尝试实现直接HTTP访问调用的出错相似。

不能确定是不是因为我的webhook修改导致的错误。登录信息没问题，巧合？

发件人: ***@***.***>
发送时间: 2022年8月5日 16:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [SunYufei/freenom] 被触发的Workers似乎总会发生错误，在编辑器中测试没问题 (Issue #11)


从日志来看，可能是 Workers 端 Freenom 登录失败

―

**Comment by lwd-temp** [comment]
拆分多步测试运行发现，可能是Workers在被cron激活时的时间限制更短，导致请求中断？分步后，错误也发生在第二步。

**Comment by PencilNavigator** [comment]
我尝试在快速编辑页面触发Cron，控制台返回的数据正常。
![图片](https://user-images.githubusercontent.com/85282140/183816617-7a2601c6-0d5f-4f36-b4ed-f3c40cef63b7.png)
