### ISSUE TITLE
通过Workers变量，加密用户名和密码

### ISSUE THREAD

**Issue by PencilNavigator** [SunYufei/freenom#14]
之前该项目使用Github Actions时，代码使用Github的Secrets加密存储账户和密码。
最近浏览发现，Cloudflare也有类似功能，即Workers变量，也可以加密存储内容。
![图片](https://user-images.githubusercontent.com/85282140/186190733-9dafd577-505b-4512-b5ae-7a3b51db665d.png)
如图所示。

在增加变量后，在代码页面将原有账户密码替换为变量名，即可实现原有功能，同时也可以保护账号密码。
更改非常简单粗暴，稍后会pr。

**Comment by SunYufei** [comment]
在 GitHub Actions 中使用 Secrets 确实有保护用户名密码的目的，Actions 中执行 shell 命令为调用 Python 脚本传递用户名密码的内容，因此需要加密操作。Workers 脚本内容在实际使用时不会暴露，若不经常修改 Freenom 用户名和密码，使用 Workers 变量是不必要的。
