### ISSUE TITLE
特性请求：支持Webhook回报执行情况

### ISSUE THREAD

**Issue by lwd-temp** [SunYufei/freenom#8]
Workers版在执行结束后请求Webhook报告执行情况（域名剩余时间、成功与否等）。

**Comment by SunYufei** [comment]
已采纳，有时间我做一下

**Comment by lwd-temp** [comment]
尝试做了一下 #9 
由于Webhook之类的东西参数不可能一样，用户似乎只能自己编辑webhook发送部分？

**Comment by SunYufei** [comment]
感谢你提出的 Webhooks + KV + Html 方案：
1. KV 存放 log 等信息
2. html 前台展示
3. Webhook 报告执行情况
我将会将本项目按照这种方案进行改造，并尽可能做出像 Actions 那样 fork + secrets 简易部署的方式
